# Generated by Django 2.1.5 on 2019-04-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tasting date')),
                ('rating', models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], default='5', max_length=1)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('origin', models.TextField(max_length=100)),
                ('SKU', models.TextField(max_length=100)),
                ('type_of', models.TextField(max_length=100)),
                ('bottle_size', models.TextField(max_length=100)),
                ('image', models.TextField()),
                ('ABV', models.FloatField(max_length=5)),
                ('maturing', models.TextField(max_length=100)),
                ('post_treatment', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tasting',
            name='whiskey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Whiskey'),
        ),
    ]
