# Generated by Django 2.1.5 on 2019-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiskey',
            name='ABV',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='SKU',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='bottle_size',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='brand',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='maturing',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='origin',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='post_treatment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='type_of',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
