# Generated by Django 2.1.5 on 2019-03-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_whiskey_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tasting date')),
                ('rating', models.CharField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (3, '⭐⭐⭐'), (2, '⭐⭐'), (1, '⭐')], default=5, max_length=1)),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Whiskey')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
