# Generated by Django 2.1.5 on 2019-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='rating',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], default='5', max_length=1),
        ),
    ]
